### PR TITLE
Enable file access mode for JSONStorage

### PR DESCRIPTION
**Pull request by jmborr**
Work done:
- [x] Optional argument `access_mode` for `JSONStorage.__init__`
- [x] Unit test for reading-only access to a database

Refs #297

### CODE REVIEW

**Comment by jmborr** [comment]
@msiemens the unit test I wrote [passes](https://dev.azure.com/msiemens/github/_build/results?buildId=84&view=logs&j=19c563d8-3dcd-57d1-cd5e-9dd946b0a29b&t=10ebb82f-a000-5f8e-b96f-1ffc81828e7d&l=69) but there's a bunch of unrelated test that don't pass. They all involve class `storage.MemoryStorage` for which I made no changes whatsoever. Are these tests also failing for the `master` branch?

**Comment by msiemens** [comment]
@jmborr I haven't forgotten about your PR. I was on vacation for the last weeks and didn't have time to come back to this

**Comment by msiemens** [comment]
@jmborr This looks good to me. Unfortunately I was working on TinyDB v4 while you authored your PR so it needs to be rebased onto `master` in order to merge this. Could you rebase your branch?

**Comment by msiemens** [comment]
This has been merged in e2de2dc888811fc7def2b8ffc99c258ec04c7f96 and released in v4.1.0! I had to squash the PR and manually cherry-pick the changes to not complicate the git log too much. Thanks for your PR 🙂

**Pull request closed without merging**
