### PR TITLE
__repr__ methods for classes TinyDB, Table and Query

### PR DESCRIPTION
**Pull request by Xarvalus**
Hello, considers https://github.com/msiemens/tinydb/issues/226.

I have added basic `__repr__` implementation for mentioned classes, would like to know if you see it as sufficient and which else classes should be implemented within the same way.

You may try the reprs with:
```
from tinydb import database, queries

print(repr(database.TinyDB('test.json')))
print(repr(database.Table(database.JSONStorage('test.json'), 'some name')))

Fruit = queries.Query()
print(repr(Fruit.type == 'peach'))
```

Achieving results:
```
TinyDB(tables={'_default'}, tables_count=1, default_table_documents_count=0, all_tables_documents_count=['_default=0'])
Table(name='some name', total=1, storage=<tinydb.storages.JSONStorage object at 0x10212c2e8>)
QueryImpl('==', ('type',), 'peach')
```

### CODE REVIEW

**Comment by cool-RR** [comment]
Thanks for volunteering to help.

The first two reprs are wrong because they use a Foo(bar) format which should only be used if the object could be reconstructed completely from Foo(Bar). I think Query can but the others can't.
So you need something like `<Table name='foo' n_entries=7>`

**Comment by cool-RR** [comment]
Also I'm not sure that you ran your code. I suggest adding tests for these `__repr__` methods.

**Comment by Xarvalus** [comment]
Thanks for feedback.

I didn't add tests as `__repr__` method are stripped away from test coverage, the above example is fairly easy and minimal to just one-time run with temporary script file for manual testing but if we prefer to spread more repr's across the classes I agree and will add those to tests.

I will adjust to the proper format shortly.

What about the sufficient info in `__repr__`s? Anything more I should add? Any thumb rule about it?

Also which classes do you prefer to also implement reprs?

**Comment by cool-RR** [comment]
1. I think that tests would be good.
2. Looking forward to seeing your new commit.
3. You've got sufficient information there.
4. These three classes are great for now.

**Comment by Xarvalus** [comment]
@cool-RR I have updated the PR, please kindly take a look

On 2.7 one of test failed, caused by https://stackoverflow.com/questions/9773121/removing-u-in-list do you suggest any best practice for keeping result the same across 2.x/3.x?

**Comment by cool-RR** [comment]
Looks good to me. I'm not the project owner, so he'll need to approve before merging.

**Comment by cool-RR** [comment]
I don't think it's important to keep the result identical in Python 2 and 3.

**Comment by Xarvalus** [comment]
Hey @msiemens meanwhile I have changed TinyDB's class repr test into regex one, just to match the Python 2.7's `u` strings issue.

Currently it passes all the checks, let know if you would like any adjustments

**Comment by Xarvalus** [comment]
Oh, sorry.. I didn't see you wrote about 2 mins before me 😄 @cool-RR okay, will push your suggestions

**Comment by cool-RR** [comment]
Great. Looks good to me. I'm not the project owner, so he'll need to approve before merging.

**Comment by msiemens** [comment]
Thanks for your work  @Xarvalus, it's much appreciated 🙂

**Comment by msiemens** [comment]
This is now released in TinyDB v3.11.1 🙃

**Comment by cool-RR** [comment]
Awesome! Thanks for the quick release!

**Pull request merged**
