### PR TITLE
configure universal wheels

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by msiemens** [comment]
I haven't really deal with Python packaging in depth for quite a while now, in what way are universal wheels better than, well, non-universal wheels? I want to merge this but also want to understand the implications of this 🙂

**Comment by graingert** [comment]
@msiemens wheels install a lot faster (even for pure python) universal wheels allow one package to be cached once for everyone.

**Comment by graingert** [comment]
you deply with `python3 setup.py sdist bdist_wheel upload`

**Comment by msiemens** [comment]
Okay, I see. Thank you for the pull request!

**Pull request merged**
