### PR TITLE
Add support for 'setup.py test'

### PR DESCRIPTION
**Pull request by jean**
```
⎇  master → upstream ↑4 U:1  ⓔ tinydb  ~/git/tinydb   python setup.py test  
running pytest
Searching for pytest
Best match: pytest 3.3.0
Processing pytest-3.3.0-py3.6.egg
Using /data/data/com.termux/files/home/git/tinydb/.eggs/pytest-3.3.0-py3.6.egg
Searching for pluggy<0.7,>=0.5
Best match: pluggy 0.6.0
Processing pluggy-0.6.0-py3.6.egg
Using /data/data/com.termux/files/home/git/tinydb/.eggs/pluggy-0.6.0-py3.6.egg
Searching for attrs>=17.2.0
Best match: attrs 17.3.0
Processing attrs-17.3.0-py3.6.egg
Using /data/data/com.termux/files/home/git/tinydb/.eggs/attrs-17.3.0-py3.6.egg
Searching for py>=1.5.0
Best match: py 1.5.2
Processing py-1.5.2-py3.6.egg
Using /data/data/com.termux/files/home/git/tinydb/.eggs/py-1.5.2-py3.6.egg
running egg_info
writing tinydb.egg-info/PKG-INFO
writing dependency_links to tinydb.egg-info/dependency_links.txt
writing top-level names to tinydb.egg-info/top_level.txt
reading manifest file 'tinydb.egg-info/SOURCES.txt'
writing manifest file 'tinydb.egg-info/SOURCES.txt'
running build_ext
=============================================================== test session starts ===============================================================platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: /data/data/com.termux/files/home/git/tinydb, inifile:                                                                                     collected 104 items                                                                                                                                                                                                                                                                                   tests/test_middlewares.py ........                                                                                                          [  7%]
tests/test_operations.py .......                                                                                                            [ 14%]
tests/test_queries.py ....................                                                                                                  [ 33%]
tests/test_storages.py ..........s                                                                                                          [ 44%]
tests/test_tables.py ........                                                                                                               [ 51%]
tests/test_tinydb.py ............................ss..........                                                                               [ 90%]
tests/test_utils.py ..........                                                                                                              [100%]

====================================================== 101 passed, 3 skipped in 8.53 seconds ====================================================== 
```

### CODE REVIEW

**Comment by jean** [comment]
The build failure is unrelated to this change, but `python setup.py test` doesn't run coverage tests yet. I'm looking into that.

**Comment by msiemens** [comment]
Hey @jean, thanks for your PR! I just wanted to merge it but I noticed that you added a commit that changes the documentation. Just for sake of consistency, could you revert that commit and create a new PR for it? Then I'll gladly merge your changes 🙂

**Comment by jean** [comment]
@msiemens sorry, took a while to get round to it ..

**Comment by msiemens** [comment]
No worries! Thanks for your contribution!

**Pull request merged**
