### PR TITLE
Subclass TinyDB from Table to make default table work with static typing

### LINKED ISSUE #372: No 'intellisense' autosuggestion of functions
I'm not sure if I've done something wrong installing TinyDB, but I'm not getting any intellisense/autocomplete, as I'm used to from most packages.

There also seem to be no type hints, maybe that's why? Is this something you'd want help with?

I'm using Pylance as my Language server in VS Code.

Here are screenshots from me using TinyDB in VSCode, note, return type is always none, so `Pylance` can't figure out what's going on.
image
image

### PR DESCRIPTION
**Pull request by corneliusroemer**
Fixes #372

### CODE REVIEW

**Comment by corneliusroemer** [comment]
CI seems to use the old tests, I added a few new ones. How can they be added to the pipeline? Is this automatic once this is merged into master?

**Comment by msiemens** [comment]
Thanks for the Pull Request, @corneliusroemer! I'll try to review it in the next couple of days.



> CI seems to use the old tests, I added a few new ones. How can they be added to the pipeline? Is this automatic once this is merged into master?

Actually the new tests should already be executed. I can't explain why they don't run either…

**Comment by msiemens** [comment]
@corneliusroemer I still haven't forgotten this PR, I hope to get around thinking this through to the end in time for the next release of TinyDB which I plan for the next week of the week after.

**Comment by msiemens** [comment]
Superseeded by 3c34154d3cca627b37b3267a4fc56380754e37b9 which has been released in TinyDB 4.5.0

**Pull request closed without merging**
