### PR TITLE
Provide a way to specify a non-default table name when creating TinyD…

### PR DESCRIPTION
**Pull request by deemson**
…B instance.

### CODE REVIEW

**Comment by msiemens** [comment]
Looks reasonable, thank you! While we're at it, could you also add a short test in `tests/test_tinydb.py`?

**Comment by deemson** [comment]
Sure.

**Comment by deemson** [comment]
moved kwargs pops to the top of init because storage instances don't recognize 'table' keyword

**Comment by msiemens** [comment]
I must have missed it in the first commit, but you introduced a new kwarg parameter to `Table.__init__()`, right? I'm conflicted on that because technically that's a breaking change (storages cannot use the `table` keyword anymore). But on the other hand I don't think this will break anyone's code as writing a storage that takes a a `table` kwarg isn't a good idea in the first place.

**Comment by deemson** [comment]
I've introduced a new `TinyDB.__init()__` kwarg and it won't be passed to storage, it is being popped out of kwargs dictionary right before the creation of storage instance.

**Comment by eugene-eeo** [comment]
May be a matter of taste but I think using a longer keyword argument like `default_table` would be preferable here as it better reflects the purpose of the parameter, and leaves less room for confusion in the future.

As an aside, I don't see why one would want to override the default table. Don't get me wrong, I like how you're handling it elegantly here, but I don't see why the application would care about the default table name.

**Comment by deemson** [comment]
I cannot argue with this type of reasoning, this is a matter of taste. I just don't want to see "_default" keyword in my storage files. I find it ugly.

Agreed on the parameter naming, though.

**Comment by msiemens** [comment]
`default_table` sounds good to me. The name of the default table indeed is a matter of taste and I see no problem with allowing to rename it.

**Comment by msiemens** [comment]
Merged! I hope to get a new release of TinyDB ready by the end of this week. Thanks everyone!

**Pull request merged**
