### PR TITLE
Sort patch - Initial Pull request to include a sort method

### PR DESCRIPTION
**Pull request by alshapton**
I'd like to have this considered as an additional method to TinyDB. Should it be accepted, I'll amend the documentation to reflect it.

### CODE REVIEW

**Comment by alshapton** [comment]
My first Pull request  - it worked locally - failed the Travis CI build - Will fix !!!! Bear with me !

**Comment by alshapton** [comment]
MMMM I dont understand how I can make the code coverage 100% - the line of code that's not covered seems to be a "for" loop - which I know is executed in all use cases and all tests I have designed....... Any ideas from the comunity ?

**Comment by msiemens** [comment]
@alshapton Thanks for the PR! I really appreciate your work, so it's a tough decision to me, wether this should go into the TinyDB core or not. I tend to think that this is better done by the users themselves. Considering the API sorting to me is something that I want to do on the _results_ of a search, but not on a database or table. `db.sort(…)` would implicate to me that I somehow sort the documents inside the database itself. A cleaner way would be something like `db.search(…).sort(…)` which I consider close enough to something like `sorted(db.search(…), key=itemgetter('name'))`.

@eugene-eeo What's your opinion on that?

**Comment by alshapton** [comment]
@msiemens I kinda see your point, but I was happy to get involved  and attempt to add some functionality - will be happy to refactor it into some extension if that's what's required.
I'll wait for you and @eugene-eeo to come back with a direction.....

**Comment by alshapton** [comment]
OK - what should we do - merge this or leave it as a small add-o n useful script listed somewhere ? I dont mind either way !!!

**Comment by msiemens** [comment]
If you want to, you can create a Wiki page called _Useful snippets_ or something like this for this and similar content.

**Comment by alshapton** [comment]
Willdo !

Andrew

**Comment by eugene-eeo** [comment]
For me this is too general to be included in TinyDB since it has very little to do with the underlying database, i.e. querying, IO operations, etc. It is easy to write a key function that one could pass to `sorted` to order data by specific keys. I think a good way to gauge whether we should include something is to ask ourselves: Could I do x better given the knowledge I have? E.g:

 - We can do querying better since:
    - we know the underlying file format
    - we have a query cache

Of course exceptions could be made where necessary for pragmatism, but I hope you see my point.

**Comment by alshapton** [comment]
@eugene-eeo  I do agree - so I think one of my original questions to @msiemens still holds though - is there a roadmap for tinydb and the desirable features that it should contain and/or external libraries and middleware and so on ....?

Also - I'll put something on the wiki page re: this , but how then do I "cancel" the PR ?

**Comment by msiemens** [comment]
> is there a roadmap for tinydb and the desirable features that it should contain and/or external libraries and middleware and so on ....?

That's a good question. As a matter of fact there's no real roadmap for TinyDB. In my mind it's more or less complete since version 3.0. Since the release of 3.0 we've mainly had bugfixes with occasional feature releases for rather small stuff (like specifying the default table name in #98 or accessing a table's name in #147). I'd prefer to have everything else implemented in external libraries/middlewares/extensions and so on. I've outlined some of my thoughts on that in https://blog.m-siemens.de/notes-on-tinydb/.

Regarding extensions, one thing we maybe might want to add is a better extension mechanism. Right now you can extend TinyDB's methods with a custom table class which unfortunately aren't composable. A plugin mechanism might fix that. On the other hand, a plugin mechanism means a lot of complexity which itself may contain or lead to bugs, so I'm undecided on that.

**Pull request closed without merging**
